[package]
name = "crystal-api"
version = "0.1.0"
edition = "2024"
authors = ["purpflow"]

[profile.release]
opt-level = 3
lto = true
strip = true

[profile.dev]
overflow-checks = true

[dev-dependencies]
winit = { version = "0.30.10", features = ["rwh_06"] }
glam = "0.30.3"
sysinfo = "0.23"
png = "0.17.16"

[[example]]
name = "main"
path = "examples/main.rs"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.0"
