#version 460

layout(set = 0, binding = 0) uniform UniformBufferObject {
    mat4 eye;
    float time;
} ubo;

struct Particle {
    vec3 position;
    vec3 velocity;
};

layout(set = 1, binding = 0) readonly buffer ParticleSSBOIn {
    Particle data[];
} pin;

layout(set = 1, binding = 1) buffer ParticleSSBOOut {
    Particle data[];
} pout;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint index = gl_GlobalInvocationID.x;

    Particle p = pin.data[index];

    pout.data[index].position = p.position + p.velocity * ubo.time;
    pout.data[index].velocity = p.velocity;
}
